name: build-and-test-on-pr.yml
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.2

      - name: Run tests
        run: go test -v ./...

      - name: Install linting tools
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.58.1

      - name: Run linters
        run: golangci-lint run

      - name: Build
        run: go build -v
